services:
  - type: web
    name: tool-update-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash run_server.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
